library_project/library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app' # for namespacing
urlpatterns = [
	path('', views.index, name='index'),
	path('search_books/', views.search_books, name='search_books'),
	path('checkout/', views.checkout, name='checkout'),
	path('my_checkouts/', views.my_checkouts, name='my_checkouts'),
	path('return_books/', views.return_books, name='return_books')
]

library_project/library_project/urls.py
from django.contrib import admin
from django.urls import path, include
from library_project import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')), # Note: all your app urls will start with this path
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
]

library_project/library_app/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Author(models.Model):
	first_name = models.CharField(max_length=250)
	last_name = models.CharField(max_length=250)
	# once you have set up a class you have to run a migrations with python \manage.py makemigrations doDoApp. Once this is successful you should have a 0001_initial in yoru omigrations folder. After any changes to models you must make another migration. this creates instructions for migrating. python manage.py migrate then actually migrates things to the app.

	def __str__(self):
		author = self.first_name + " " + self.last_name
		return author

class Book(models.Model):
	title = models.CharField(max_length=250)#unique makes it so that you can't repeat them
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	checked_out_to_whom = models.CharField(max_length=250)
	checked_out_when = models.DateTimeField(default=datetime.now())

	# pub_date = models.DateTimeField(default=datetime.now())
	# once you have set up a class you have to run a migrations with python \manage.py makemigrations doDoApp. Once this is successful you should have a 0001_initial in yoru omigrations folder. After any changes to models you must make another migration. this creates instructions for migrating. python manage.py migrate then actually migrates things to the app.

	def __str__(self):
		return self.title

library_project/library_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book
from datetime import datetime
from datetime import timedelta #lets you change the date to make a due date 20 days from now

def index(request):
	if request.user.is_authenticated:
		username = request.user.username
	else: username = "x"
	book_list = Book.objects.all()
	result = ""
	context = {'book_list': book_list, 'search_result': result, "username": username}
	print("hello!")
	return render(request, 'library_app/index.html', context)


def search_books(request):
	if request.method == 'GET':
		print("you called search_book")
		search_query = request.GET['search_box']
		searched_books = []
		titles = Book.objects.filter(title__icontains=search_query)
		first_names =Book.objects.filter(author__first_name__icontains=search_query)
		last_names = Book.objects.filter(author__last_name__icontains=search_query)
		searched_books.extend(titles.union(first_names, last_names))
		# searched_book.append(Book.objects.filter(author=search_query))
		print(f'the book you looked for is {searched_books}')
		context = {'book_list': searched_books}
		return render(request, 'library_app/index.html', context)


def checkout(request):
	if request.method == 'POST':
		if request.user.is_authenticated:
			username = request.user.username
			for book in request.POST:
				if book.startswith('book_'):
					book_id = book[5:]
					booky = Book.objects.get(id=book_id)
					if booky.checked_out_to_whom == "":
						booky.checked_out_to_whom=username
						booky.checked_out_when=datetime.now()+timedelta(20)#adds 20 days from today for due date
						print(f'the day is {datetime.now()}')
						booky.save()
					else: return HttpResponse(f'{booky.title} is already checked out to someone else. Nice try, hacker!')
					print(f'you checked out {booky}')
			return redirect('library_app:my_checkouts')
		else:
			# return redirect('library_project:accounts/login')
			# return redirect('http://localhost:8000/accounts/login/')
			return redirect('login')


def my_checkouts(request):
	if request.user.is_authenticated:
		username = request.user.username
		my_checkouts = Book.objects.filter(checked_out_to_whom=username)
		print(my_checkouts)
		context = {'my_checkouts': my_checkouts, 'username': username}
		return render(request, 'library_app/my_checkouts.html', context)
	else:
		return HttpResponse('checkouts! oh yeah!')


def return_books(request):
	for book in request.POST:
		print(book)
		if book.startswith('book_'):
			book_id = book[5:]
			print(book_id)
			booky = Book.objects.get(id=book_id)
			booky.checked_out_to_whom=""
			booky.save()
	return redirect('library_app:my_checkouts')
	return HttpResponse('get ye back to the library')

library_project/library_project/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.clean_password2()
			user = authenticate(username=username, password=password)
			if user:
				login(request, user)
			return redirect('library_app:index')
		else:
			return HttpResponse('Invalid form')
	context = {'form': UserCreationForm()}
	return render(request, 'registration/register.html', context)

library_project/library_app/templates/library_app/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <h1> this is a base_generic library in the app!!!! wheee!</h1>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        <li><a href="{% url 'library_app:index' %}">Home</a></li>
        <li><a href="">All books</a></li>
        <li><a href="">My checkouts</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

library_project/library_app/templates/library_app/index.html
{% extends "base_generic.html" %}

{% block content %}

<form action="{%url 'library_app:search_books' %}" method="get">
	<input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
	<button id="search_submit" type="submit" >Submit</button>
</form>

<form action="{%url 'library_app:checkout'  %}" method="post">
	{% csrf_token%}
	<ul class="no_bullets">
	<p></p>
			{% for book in book_list %}
			<div class="books">
				<li>
					<h3>Title: {{book.title}}</h3>
					<p> Author: {{book.author}}</p>
					{% if book.checked_out_to_whom == username %}
					This book is checked out to you
					{% elif book.checked_out_to_whom == "" %}
					<input type="checkbox" class="books" name="book_{{book.id}}"> Check out this title
					{% else %}
					This book is currently checked out to another user
					{% endif %}
					<p></p>
				</li>
			</div>
			{% endfor %}
			</ul>
			<button type="submit" >Check out</button>
</form>





{% endblock %}

library_project/library_app/templates/library_app/my_checkouts.html
{% extends "base_generic.html" %}



{% block content %}


<h4>You have the following books checked out:</h4>


<form action="{%url 'library_app:return_books'  %}" method="post">
	{% csrf_token%}
	<ul class="no_bullets">
	<p></p>
			{% for book in my_checkouts %}
			<div class="books">
				<li>
					<h3>Title: {{book.title}}</h3>
					<p> Author: {{book.author}}</p>
					<p> Due: {{book.checked_out_when|date:"D, d M Y" }}
					<input type="checkbox" name="book_{{book.id}}"> Return this title
					<p></p>
				</li>
			</div>
			{% endfor %}
			</ul>
			<button type="submit" >Return selected titles</button>
</form>




{% endblock %}

library_project/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- Add additional CSS in static file -->


  {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'library_app/style.css' %}"/>
</head>
<body>



  <h1> Welcome to the library! </h1>
	<h2>Hello {{username}}</h2>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        <a href="{% url 'library_app:index' %}">Home</a></br>
				{% if user.is_authenticated %}
					<a href="{% url 'library_app:my_checkouts' %}">My checkouts</a></br>
					<a href="{% url 'logout' %}">Logout</a></br>
				{% else %}
					<a href="{% url 'register' %}">Register</a></br>
					<a href="{% url 'login' %}">Login</a></br>
					{% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>